create table if not exists public.inventory_adjustment_history (
    id bigint generated by default as identity primary key,
    plan_id bigint,
    business_key text not null default '',
    item_code text not null,
    color text not null default '',
    plan_required_qty numeric not null default 0,
    requested_adjust_qty numeric not null default 0,
    applied_adjust_qty numeric not null default 0,
    inventory_before_qty numeric not null default 0,
    inventory_after_qty numeric not null default 0,
    reason text not null default '',
    updated_by text not null default '',
    updated_at text not null default ''
);

create index if not exists inventory_adjustment_history_plan_idx
    on public.inventory_adjustment_history (plan_id);

create index if not exists inventory_adjustment_history_item_idx
    on public.inventory_adjustment_history (item_code, color, updated_at);
