create table if not exists public.code_mapping (
    id bigint generated by default as identity primary key,
    product_code text not null,
    product_name text not null default '',
    part_name_raw text not null default '',
    part_name_normalized text not null,
    color text not null default '',
    updated_at text not null default ''
);

create unique index if not exists code_mapping_unique_key
    on public.code_mapping (product_code, color, part_name_normalized);

create index if not exists code_mapping_part_lookup
    on public.code_mapping (part_name_normalized, color);
